// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vvygrjjtvvlhahcbgcia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2eWdyamp0dnZsaGFoY2JnY2lhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE5Nzk2NjksImV4cCI6MjA4NzU1NTY2OX0.2aXvM1q4_jqN1mHshoISFm9wGtP2p09CdLEJ9E55eXk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});